# -*- ruby -*-
# encoding: utf-8

task :default do
  puts 'uasge rake [build] [publish]'
  puts
  puts 'Options:'
  puts 'build: builds the publication for de-DE and en-US'
  puts 'publish: copies the publication to the right dir in saigkill.github.io/docs, adds, commits and pushs'
end

task :build do
  system('publican build --formats=html --langs=de-DE,en-US')
end

task :publish do
  system('cp -a * ~/RubymineProjects/saigkill.github.io/docs/hoe-reek')
  system('git add *')
  system('git commit -m "Updated docs for hoe-reek"')
  system('git push')
end